TYPE_MAP = {
    "RECRUIT_INFANTRY": "INFANTRY",
    "RECRUIT_LIGHT_CAVALRY": "CAVALRY",
    "SUPPLY_CARAVAN": "SUPPLY",
    "HEAVY_CAVALRY": "CAVALRY",
    "LINE_INFANTRY": "INFANTRY",
    "LIGHT_INFANTRY": "INFANTRY",
    "HEAVY_LINE_INFANTRY": "INFANTRY",
    "LIGHT_CAVALRY": "CAVALRY",
    "ARTILLERY": "ARTILLERY",
    "LIGHT_ARTILLERY": "ARTILLERY",
    "RECRUIT_ARTILLERY": "ARTILLERY",
}

SUPPLY_MULT = {
    "INFANTRY": 10,
    "CAVALRY": 15,
    "ARTILLERY": 80,
}