UNITS = {
    "FRA_Royal_Recruits": "Royal Recruits",
    "FRA_French_Fusiliers": "French Fusiliers",
    "FRA_French_Veteran_Fusiliers": "French Veteran Fusiliers",
    "FRA_French_Grenadiers": "French Grenadiers",
    "FRA_French_Provincial_Cavalry": "French Provincial Cavalry",
    "FRA_French_Hussars": "French Hussars",
    "FRA_French_Gendarmerie": "French Gendarmerie",
    "FRA_French_Dragoons": "French Dragoons",
    "FRA_French_Gentleman_Cavalry": "French Gentleman Cavalry",
    "FRA_French_Royal_Cavalry": "French Royal Cavalry",
    "FRA_French_Reserve_Artillery": "French Battalion Artillery",
    "FRA_French_Field_Artillery": "French Field Artillery",
    "FRA_Irish_Fusiliers": "Irish Fusiliers",
    "FRA_Irish_Grenadiers": "Irish Grenadiers",
    "FRA_German_Fusiliers": "German Fusiliers",
    "FRA_German_Grenadiers": "German Grenadiers",
    "FRA_Swiss_Fusiliers": "Swiss Fusiliers",
    "FRA_Swiss_Grenadiers": "Swiss Grenadiers",
    "FRA_Volontaires_Fusiliers": "Volontaires Fusiliers",
    "FRA_Chasseurs": "Chasseurs",
    "FRA_French_Royaux_Grenadiers": "Volontaires Grenadiers",
    "FRA_Volontaires_Provincial_Cavalry": "Volontaires Provincial Cavalry",
    "FRA_Volontaires_Hussars": "Volontaires Hussars",
    "FRA_Volontaires_Dragoons": "Volontaires Dragoons",
    "FRA_Diesbach_Fusiliers": "The Diesbach Fusiliers",
    "FRA_Royal_Scots_Fusiliers": "The Royal Scots Fusiliers",
    "FRA_Royal_Deux_Ponts_Grenadiers": "The Royal Swedish Fusiliers",
    "FRA_Grenadiers_Of_France": "The Grenadiers of France",
    "FRA_French_Guards": "The French Guards",
    "FRA_Swiss_Guards": "The Swiss Guards",
    "FRA_Musketeers_Of_The_Guard": "Musketeers of the Guard",
    "FRA_Royal_Allemand_Cavalry": "Royal-Allemand Cavalry",
    "FRA_Grenadiers_A_Cheval": "Grenadiers a Cheval",
    "FRA_Fifth_Royal_Artillery": "5th Royal Artillery",
    "GBR_British_Recruits": "Redcoat Recruits",
    "GBR_British_Foot": "British Foot",
    "GBR_British_Veteran_Foot": "British Veteran Foot",
    "GBR_British_Grenadiers": "British Grenadiers",
    "GBR_British_Provincial_Cavalry": "British Provincial Cavalry",
    "GBR_British_Light_Dragoons": "British Light Dragoons",
    "GBR_British_Dragoons": "British Dragoons",
    "GBR_British_Reserve_Artillery": "British Battalion Artillery",
    "GBR_British_Field_Artillery": "British Field Artillery",
    "GBR_Highland_Foot": "Highland Foot",
    "GBR_Highland_Grenadiers": "Highland Grenadiers",
    "GBR_German_Recruits": "Subsidy Recruits",
    "GBR_German_Landmiliz": "Hanoverian Landmiliz",
    "GBR_German_Jaegers": "Subsidy Jaegers",
    "GBR_German_Provincial_Cavalry": "Subsidy Provincial Cavalry",
    "GBR_German_Reserve_Artillery": "Subsidy Battalion Artillery",
    "GBR_German_Field_Artillery": "Subsidy Field Artillery",
    "GBR_Brunswicker_Musketeers": "Brunswicker Musketeers",
    "GBR_Hanoverian_Foot": "Hanoverian Foot",
    "GBR_Hanoverian_Grenadiers": "Hanoverian Grenadiers",
    "GBR_Hanoverian_Cavalry": "Hanoverian Cavalry",
    "GBR_Hessian_Musketeers": "Hessian Musketeers",
    "GBR_Hessian_Grenadiers": "Hessian Grenadiers",
    "GBR_Hessian_Cavalry": "Hessian Cavalry",
    "GBR_Campbells_Highlanders": "The Campbell's Highlanders",
    "GBR_Legion_Britannique_Musketeers": "The Legion Britannique Musketeers",
    "GBR_Royal_Welch_Fusiliers": "The Royal Welch Fusiliers",
    "GBR_Hanoverian_Foot_Guards": "The Hanoverian Foot Guards",
    "GBR_Coldstream_Guards": "The Coldstream Guards",
    "GBR_Von_Roth_Hussars": "The von Roth Hussars",
    "GBR_Bueckeberg_Carabiniers": "The Bueckeburg Carabiniers",
    "GBR_First_Dragoon_Guards": "The 1st Dragoon Guards",
    "GBR_Royal_Horse_Guards": "The Royal Horse Guards",
    "GBR_Schaumburg_Lippe_Fusiliers": "The Schaumburg-Lippe Artillery",
    "RUS_Volunteer_Recruits": "Serf Recruits",
    "RUS_Musketeers": "Russian Musketeers",
    "RUS_Drilled_Musketeers": "Russian Veteran Musketeers",
    "RUS_Grenadiers": "Russian Grenadiers",
    "RUS_Rider_Recruits": "Russian Rider Recruits",
    "RUS_Provincial_Cavalry": "Russian Provincial Cavalry",
    "RUS_Hussars": "Russian Hussars",
    "RUS_Dragoons": "Russian Dragoons",
    "RUS_Cuirassiers": "Russian Cuirassiers",
    "RUS_Horse_Grenadiers": "Russian Horse Grenadiers",
    "RUS_Artillerist_Recruits": "Russian Artillery Recruits",
    "RUS_Reserve_Artillery": "Russian Battalion Artillery",
    "RUS_Field_Artillery": "Russian Field Artillery",
    "RUS_Frontier_Recruits": "Frontier Recruits",
    "RUS_Pandurs": "Pandur Musketeers",
    "RUS_Cossack_Riders": "Cossack Cavalry",
    "RUS_Settled_Hussars": "Settled Hussars",
    "RUS_Orenburg_Cossacks": "Slobodian Cossacks",
    "RUS_Don_Cossacks": "Don Cossacks",
    "RUS_Serf_Recruits": "Observation Recruits",
    "RUS_Observation_Musketeers": "Observation Musketeers",
    "RUS_Observation_Fusiliers": "Observation Fusiliers",
    "RUS_Observation_Grenadiers": "Observation Grenadiers",
    "RUS_Observation_Reserve_Artillery": "Observation Field Artillery",
    "RUS_Pskovskiy_Musketeers": "The Pskovsky Musketeers",
    "RUS_Kievskiy_Musketeers": "The Kievskiy Musketeers",
    "RUS_Möller_Sakomelsky_Jägers": "The Moeller-Sakomelsky Jaegers",
    "RUS_Dmitrivich_Dragoons": "The 1st Grenadiers",
    "RUS_Preobrazhenskiy_Life_Guards": "The Preobrazhenskiy Life Guards",
    "RUS_Chuguev_Cossacks": "The Chuguev Cossacks",
    "RUS_Serbski_Hussars": "The Serbski Hussars",
    "RUS_Tverskoy_Dragoons": "The Tverskoy Dragoons",
    "RUS_Münnich_Cuirassiers": "The Muennich Cuirassiers",
    "RUS_Shuvalov_Howitzers": "The Shuvalov Artillery",
    "AUS_German_Recruit": "Crownland Recruits",
    "AUS_German_Fusiliers": "Austrian Fusiliers",
    "AUS_German_Drilled_Fusiliers": "Austrian Veteran Fusiliers",
    "AUS_Jaegers": "Austrian Jaegers",
    "AUS_German_Grenadiers": "Austrian Grenadiers",
    "AUS_Provincial_Cavalry": "Austrian Chevauleger",
    "AUS_Dragoons": "Austrian Dragoons",
    "AUS_Cuirassiers": "Austrian Cuirassiers",
    "AUS_Horse_Grenadiers": "Austrian Horse Grenadiers",
    "AUS_Reserve_Artillery": "Austrian Battalion Artillery",
    "AUS_Field_Artillery": "Austrian Field Artillery",
    "AUS_Dutch_Field_Artillery": "Dutch Field Artillery",
    "AUS_Guard_Artillery": "Austrian Veteran Artillery",
    "AUS_Foreign_Recruit": "Hungarian Recruits",
    "AUS_Hungarian_Fusiliers": "Hungarian Fusiliers",
    "AUS_Hungarian_Grenadiers": "Hungarian Grenadiers",
    "AUS_Hussars": "Hungarian Hussars",
    "AUS_Frontier_Cavalry": "Hungarian Veteran Hussars",
    "AUS_Grenzer_Recruits": "Grenzer Recruits",
    "AUS_Grenzer_Infantry": "Grenzer Fusiliers",
    "AUS_Grenzer_Sharpshooters": "Grenzer Sharpshooters",
    "AUS_Grenzer_Grenadiers": "Grenzer Grenadiers",
    "AUS_Grenzer_Provincial_Cavalry": "Grenzer Provincial Cavalry",
    "AUS_Grenz_Hussars": "Grenzer Hussars",
    "AUS_Deutschmeister_Fusiliers": "The Deutschmeister Fusiliers",
    "AUS_Esterházy_Fusiliers": "The Esterhazy Fusiliers",
    "AUS_De_Ligne_Fusiliers": "The De Ligne Fusiliers",
    "AUS_Otocaner_Grenzers": "The Otocaner Grenzers",
    "AUS_Seriman_Grenadiers": "The De Vins Grenadiers",
    "AUS_Green_Loudon_Grenadiers": "The Green Loudon Grenadiers",
    "AUS_Kaiser_Franz_Hussars": "The Kaiser Franz Hussars",
    "AUS_Erzherzog_Joseph_Dragoons": "The Erzherzog Joseph Dragoons",
    "AUS_Alt_Modena_Cuirassiers": "The Alt-Modena Cuirassiers",
    "AUS_Perkopp_Artillery": "The Perkopp Artillery",
}